## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

Note:
1. The variable that is the target for the model is "IS_SUCCESSFUL"
2. Currently, all other variables are features for the model, e.g. "APPLICATION_TYPE", "AFFILIATION", etc.

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(["EIN", "NAME"], axis=1,inplace=True)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [28]:
unique_counts = application_df.nunique()
print(unique_counts)

APPLICATION_TYPE             9
AFFILIATION                  6
CLASSIFICATION               6
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# For columns that have more than 10 unique values, determine the number of data points for each unique value.
# Based on the results above, there are three columns with more than 10 unique values:
# APPLICATION_TYPE
# CLASSIFICATION
# ASK_AMT
value_counts_application_type = application_df["APPLICATION_TYPE"].value_counts()
value_counts_classification = application_df["CLASSIFICATION"].value_counts()
value_counts_ask_amt = application_df["ASK_AMT"].value_counts()

In [9]:
#Look at "APPLICATION_TYPE" value counts to identify and replace with "Other"
print(value_counts_application_type)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9','T13','T12','T2','T14','T25','T15','T29','T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

NameError: name 'application_types_to_replace' is not defined

In [10]:
#Look at "CLASSIFICATION" value counts to identify and replace with "Other"
print(value_counts_classification)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1370        1
C4120        1
C2600        1
C2190        1
C6100        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [12]:
# Look at CLASSIFICATION value counts >1
value_counts_classification_greater_than_1 = value_counts_classification[value_counts_classification>1]
print(value_counts_classification_greater_than_1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [13]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

In [14]:
#copied_df= application_df.copy() make a copy so if my code doesn't work, I don't need to start from the beginning!
values_to_replace = application_df["CLASSIFICATION"].value_counts().index[-66:]
application_df["CLASSIFICATION"]=application_df["CLASSIFICATION"].replace(values_to_replace,"Other")
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [16]:
# Convert categorical data to numeric with `pd.get_dummies`
#  create a list of the columns containing categorical data
#categorical_columns = ["Application_Type"]
copied_df= application_df.copy()
application_df_new = pd.get_dummies(application_df)
application_df_new.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [29]:
#use the following code to confirm the features that are used in the model
unique_counts_new = application_df_new.nunique()
print(unique_counts_new)

STATUS                             2
ASK_AMT                         8747
IS_SUCCESSFUL                      2
APPLICATION_TYPE_Other             2
APPLICATION_TYPE_T10               2
APPLICATION_TYPE_T19               2
APPLICATION_TYPE_T3                2
APPLICATION_TYPE_T4                2
APPLICATION_TYPE_T5                2
APPLICATION_TYPE_T6                2
APPLICATION_TYPE_T7                2
APPLICATION_TYPE_T8                2
AFFILIATION_CompanySponsored       2
AFFILIATION_Family/Parent          2
AFFILIATION_Independent            2
AFFILIATION_National               2
AFFILIATION_Other                  2
AFFILIATION_Regional               2
CLASSIFICATION_C1000               2
CLASSIFICATION_C1200               2
CLASSIFICATION_C2000               2
CLASSIFICATION_C2100               2
CLASSIFICATION_C3000               2
CLASSIFICATION_Other               2
USE_CASE_CommunityServ             2
USE_CASE_Heathcare                 2
USE_CASE_Other                     2
USE_CASE_Preservation              2
USE_CASE_ProductDev                2
ORGANIZATION_Association           2
ORGANIZATION_Co-operative          2
ORGANIZATION_Corporation           2
ORGANIZATION_Trust                 2
INCOME_AMT_0                       2
INCOME_AMT_1-9999                  2
INCOME_AMT_10000-24999             2
INCOME_AMT_100000-499999           2
INCOME_AMT_10M-50M                 2
INCOME_AMT_1M-5M                   2
INCOME_AMT_25000-99999             2
INCOME_AMT_50M+                    2
INCOME_AMT_5M-10M                  2
SPECIAL_CONSIDERATIONS_N           2
SPECIAL_CONSIDERATIONS_Y           2
dtype: int64

In [21]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y=application_df_new['IS_SUCCESSFUL']
X=application_df_new.drop(columns='IS_SUCCESSFUL')
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42)

In [22]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [38]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn_model = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=43))

# Second hidden layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=30, activation="relu"))
# Output layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
# Check the structure of the model
nn_model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_36 (Dense)            (None, 80)                3520

 dense_37 (Dense)            (None, 30)                2430

 dense_38 (Dense)            (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [40]:
#create a model checkpoint callback to save the model's weights every 5 epochs
from tensorflow.keras.callbacks import ModelCheckpoint  #need to place this at the beginning of my code...

# Define the filepath where the model weights will be saved
filepath = "model_weights.h5"

# Create a ModelCheckpoint callback to save the model weights every 5 epochs
checkpoint_callback = ModelCheckpoint(filepath,
                                      save_weights_only=True,
                                      save_freq='epoch',
                                      period=5)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [41]:
# Compile the model
#  YOUR CODE GOES HERE
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [42]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100, callbacks=[checkpoint_callback])

Epoch 1/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5705 - accuracy: 0.7194
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5558 - accuracy: 0.7264
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5529 - accuracy: 0.7301
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5516 - accuracy: 0.7301
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7313
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7322
Epoch 7/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5482 - accuracy: 0.7322
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7343
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7331
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7327
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7341
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7334
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7337
Epoch 14/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5447 - accuracy: 0.7336
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7335
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7344
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7341
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7353
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7350
Epoch 20/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5426 - accuracy: 0.7346
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5424 - accuracy: 0.7351
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7358
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7350
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7373
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7365
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7365
Epoch 27/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5414 - accuracy: 0.7362
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7363
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7364
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7369
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7368
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7376
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7373
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5399 - accuracy: 0.7379
Epoch 35/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5393 - accuracy: 0.7367
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7366
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7371
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7376
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7379
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7376
Epoch 41/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5386 - accuracy: 0.7371
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7371
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7376
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7378
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7379
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7385
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7378
Epoch 48/100
804/804 [==============================] - 4s 6ms/step - loss: 0.5385 - accuracy: 0.7381
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7377
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7385
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7377
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7381
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7386
Epoch 54/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5376 - accuracy: 0.7390
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7383
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7376
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7380
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7388
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7391
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7394
Epoch 61/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5369 - accuracy: 0.7383
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7388
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7397
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7382
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7397
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7392
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7385
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5360 - accuracy: 0.7391
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7391
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7397
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7392
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7394
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7388
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.7399
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5355 - accuracy: 0.7385
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5360 - accuracy: 0.7395
Epoch 77/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5359 - accuracy: 0.7399
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7398
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7394
Epoch 80/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5351 - accuracy: 0.7388
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7404
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7404
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7408
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7393
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7397
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.7400
Epoch 87/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5350 - accuracy: 0.7386
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7397
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7405
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7392
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7397
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7393
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5347 - accuracy: 0.7396
Epoch 94/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7402
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7392
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7399
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7392
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7400
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7405
Epoch 100/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5342 - accuracy: 0.7403

In [43]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 2s - loss: 0.5604 - accuracy: 0.7294 - 2s/epoch - 7ms/step
Loss: 0.5603907108306885, Accuracy: 0.7294460535049438

In [47]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn_model.save('AphabetSoupCharity.h5')

In [48]:
from google.colab import files
files.download('AphabetSoupCharity.h5')